---
title: "Data Simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data Simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---




``` r
library(abn)
#> Error in library(abn): there is no package called 'abn'
```

In this vignette, we will simulate data from an additive Bayesian network and compare it to the original data.

# Fit a model to the original data

First, we will fit a model to the original data that we will use to simulate new data from.
We will use the `ex1.dag.data` data set and fit a model to it.


``` r
# Load example data
mydat <- ex1.dag.data
#> Error in eval(expr, envir, enclos): object 'ex1.dag.data' not found

# Set the distribution of each node
mydists <- list(b1="binomial",
                p1="poisson",
                g1="gaussian",
                b2="binomial",
                p2="poisson",
                b3="binomial",
                g2="gaussian",
                b4="binomial",
                b5="binomial",
                g3="gaussian")

# Build the score cache
mycache <- buildScoreCache(data.df = mydat,
                           data.dists = mydists,
                           method = "bayes",
                           max.parents = 4)
#> Error in buildScoreCache(data.df = mydat, data.dists = mydists, method = "bayes", : could not find function "buildScoreCache"

# Structure learning
mp.dag <- mostProbable(score.cache = mycache)
#> Error in mostProbable(score.cache = mycache): could not find function "mostProbable"

# Estimate the parameters
myfit <- fitAbn(object = mp.dag)
#> Error in fitAbn(object = mp.dag): could not find function "fitAbn"

# Plot the DAG
plot(myfit)
#> Error in eval(expr, envir, enclos): object 'myfit' not found
```

# Simulate new data

Based on the `abnFit` object, we can simulate new data.
By default `simulateAbn()` synthesizes 1000 new data points.


``` r
mydat_sim <- simulateAbn(object = myfit)
#> Error in simulateAbn(object = myfit): could not find function "simulateAbn"
str(mydat_sim)
#> Error in eval(expr, envir, enclos): object 'mydat_sim' not found
```

In the background, the `simulateAbn()` function translates the `abnFit` object into a BUGS model and calls the `rjags` package to simulate new data.

Especially for debugging purposes, it can be usefull to manually inspect the BUGS file that is generated by `simulateAbn()`.
This can be done by not running the simulation with `run.simulation = FALSE` and print the BUGS file to console with `verbose = TRUE`.


``` r
# Simulate new data and print the BUGS file to the console
simulateAbn(object = myfit,
            run.simulation = FALSE,
            verbose = TRUE)
```

To store the BUGS file for reproducibility or manual inspection, we can set the `bugsfile` argument to a file name to save the BUGS file to disk.

# Compare the original and simulated data

We can compare the original and simulated data by plotting the distributions of the variables.


``` r
# order the columns of mydat equal to mydat_sim
mydat <- mydat[, colnames(mydat_sim)]
#> Error in eval(expr, envir, enclos): object 'mydat' not found
```


``` r
library(ggplot2)
library(gridExtra)

# Create a list of variables
variables <- names(mydat)
#> Error in eval(expr, envir, enclos): object 'mydat' not found

# Initialize an empty list to store plots
plots <- list()

# For each variable
for (i in seq_along(variables)) {
  # Check if the variable is numeric
  if (is.numeric(mydat[[variables[i]]])) {
    # Create a histogram for the variable in mydat
    p1 <- ggplot(mydat, aes(!!as.name(variables[i]))) +
      geom_histogram(binwidth = 0.5, fill = "skyblue", color = "black") +
      labs(title = paste("mydat", variables[i]), x = variables[i], y = "Count") +
      theme_minimal()

    # Create a histogram for the variable in mydat_sim
    p2 <- ggplot(mydat_sim, aes(!!as.name(variables[i]))) +
      geom_histogram(binwidth = 0.5, fill = "skyblue", color = "black") +
      labs(title = paste("mydat_sim", variables[i]), x = variables[i], y = "Count") +
      theme_minimal()
  } else {
    # Create a bar plot for the variable in mydat
    p1 <- ggplot(mydat, aes(!!as.name(variables[i]))) +
      geom_bar(fill = "skyblue", color = "black") +
      labs(title = paste("mydat", variables[i]), x = variables[i], y = "Count") +
      theme_minimal()

    # Create a bar plot for the variable in mydat_sim
    p2 <- ggplot(mydat_sim, aes(!!as.name(variables[i]))) +
      geom_bar(fill = "skyblue", color = "black") +
      labs(title = paste("mydat_sim", variables[i]), x = variables[i], y = "Count") +
      theme_minimal()
  }

  # Combine the plots into a grid
  plots[[i]] <- arrangeGrob(p1, p2, ncol = 2)
}
#> Error in eval(expr, envir, enclos): object 'variables' not found
```



``` r
# Print all plots
do.call(grid.arrange, c(plots, ncol = 1))
#> Error in unit(rep(1, nrow), "null"): 'x' and 'units' must have length > 0
```

The plots show that the distributions of the original and simulated data are similar.

