# Workflow is triggered on label and check installation on various operating systems
# This action is adapted from https://github.com/t4d-gmbh/stubbed_versioning
name: Windows Install

on:
  pull_request:
    types: [ labeled ]

env:
  LABEL_CHECK: 'windowsInstall::check'
  LABEL_SUCCESS: 'windowsInstall::passed'
  LABEL_FAILURE: 'windowsInstall::failed'
  BUILD_LOC: "./build"
  JAGS_MAJORV: '4'
  JAGS_VERSION: '4.3.1'
  JAGS_URL: "https://sourceforge.net/projects/mcmc-jags/files/JAGS"

permissions:
  packages: read
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  setup-and-install:
    if: ${{ github.event.label.name == 'windowsInstall::check' }}
    name: windows-latest (${{ matrix.config.r }})
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    strategy:
      fail-fast: false
      matrix:
        config:
          - {r: 'release',}
          # - {r: '4.1',}
          - {r: 'devel', http-user-agent: 'release'}
          - {r: 'oldrel-1',}
          - {r: 'oldrel-2',}
          # - {r: 'oldrel-3',}

    steps:

      # - name: Install GSL binaries with cygwin
      #   uses: cygwin/cygwin-install-action@master
      - name: prepare windows 1/2
        run: |
            install.packages("devtools", repos=c(CRAN="https://cran.r-project.org"))
        shell: Rscript {0}

      # - name: prepare windows 2/2
      #   run: |
      #       $progressPreference = 'silentlyContinue'
      #       Write-Information "Downloading WinGet and its dependencies..."
      #       Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
      #       Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
      #       Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.6/Microsoft.UI.Xaml.2.8.x64.appx -OutFile Microsoft.UI.Xaml.2.8.x64.appx
      #       Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
      #       Add-AppxPackage Microsoft.UI.Xaml.2.8.x64.appx
      #       Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
      #       winget install --id Git.Git -e --source winget

      - name: install GSL
        run: |
          Import-Module bitstransfer
          New-Item -ItemType Directory -Force -Path "C:\Program Files\cygwin"
          start-bitstransfer -source https://cygwin.com/setup-x86_64.exe "C:\Program Files\cygwin\setup-x86_64.exe"
          Start-Process -Wait -FilePath "C:\Program Files\cygwin\setup-x86_64.exe" -ArgumentList "--quiet-mode --packages=gsl --site=https://cygwin.mirror.constant.com" -PassThru

      - name: install JAGS
        run: |
          Import-Module bitstransfer
          New-Item -ItemType Directory -Force -Path "C:\Program Files\JAGS\JAGS-${{ env.JAGS_VERSION }}"
          start-bitstransfer -source ${{ env.JAGS_URL }}/${{ env.JAGS_MAJORV }}.x/Windows/JAGS-${{ env.JAGS_VERSION }}.exe/download  "C:\Program Files\JAGS\JAGS-${{ env.JAGS_VERSION }}\JAGS-${{ env.JAGS_VERSION }}.exe"
          Start-Process -Wait -FilePath "C:\Program Files\JAGS\JAGS-${{ env.JAGS_VERSION }}\JAGS-${{ env.JAGS_VERSION }}.exe" -ArgumentList "/S" -PassThru

      - name: install rjags separately
        run: |
            Sys.setenv(JAGS_HOME="C:/Program Files/JAGS/JAGS-${{ env.JAGS_VERSION }}")
            install.packages("rjags", repos=c(CRAN="https://cran.r-project.org"))
            library("rjags")
        shell: Rscript {0}

      - name: install INLA
        run: |
            install.packages("INLA", repos = c(CRAN = "https://cran.r-project.org", INLA = "https://inla.r-inla-download.org/R/stable"), dep = TRUE)
        shell: Rscript {0}

      - name: installing dependencies from BiocManager
        run: |
          if (!requireNamespace("BiocManager", quietly = TRUE))
              install.packages("BiocManager", repos=c(CRAN="https://cran.r-project.org"))
          BiocManager::install("Rgraphviz")
          BiocManager::install("graph")
        shell: Rscript {0}

      - name: install abn from GitHub
        run: |
            devtools::install_github("furrer-lab/abn", ref="detailed-installation-instructions", dependencies=c("Depends", "Imports", "LinkingTo"))
        shell: Rscript {0}

      - name: fetch the repository from GitHub
        uses: actions/checkout@v4

      - name: deactivate the renv
        run: |
            renv::deactivate()
        shell: Rscript {0}

      - name: running testhat
        run: |
            devtools::test('./')
        shell: Rscript {0}

  report_Windows_setup:
    if: ${{ (success() || failure()) }}
    needs:
      - setup-and-install 
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if on demand tasks succeeded
        run: |
          gh pr edit ${{ env.EVENT }} --remove-label ${{ env.LABEL_CHECK }} --repo ${{ env.OWNER }}/${{ env.REPO }}
          if [ ${{ needs.setup-and-install.result }} == "success" ]; then
            gh pr edit ${{ env.EVENT }} --remove-label ${{ env.LABEL_FAILURE }} --repo ${{ env.OWNER }}/${{ env.REPO }}
            gh pr edit ${{ env.EVENT }} --add-label ${{ env.LABEL_SUCCESS }} --repo ${{ env.OWNER }}/${{ env.REPO }}
            echo "### ${{ github.event.label.url }} passed! :rocket:" >> $GITHUB_STEP_SUMMARY
            exit 0
          elif [ ${{ needs.setup-and-install.result }} == "failure" ]; then
            gh pr edit ${{ env.EVENT }} --remove-label ${{ env.LABEL_SUCCESS }} --repo ${{ env.OWNER }}/${{ env.REPO }}
            gh pr edit ${{ env.EVENT }} --add-label ${{ env.LABEL_FAILURE }} --repo ${{ env.OWNER }}/${{ env.REPO }}
            echo "### ${{ github.event.label.url }} failed!" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            gh pr edit ${{ env.EVENT }} --add-label ${{ env.LABEL_CHECK }} --repo ${{ env.OWNER }}/${{ env.REPO }}
            echo "On demand task outcome was ${{ needs.setup-and-install.outcome }}"
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT: ${{ github.event.number }}  # This is either the issue or pr
