name: Publish Release

# Only trigger, when CRAN-like checks succeed 
on:
  push:
    branches: [ main, streamline-release-process ]
  # workflow_run:
  #   branches: [ main, streamline-release-process ]
  #   workflows: ["CRAN-like checks"]
  #   types:
  #     - completed

env:
  BUILD_LOC: "./build"

jobs:
   publish:
     runs-on: ubuntu-22.04
     # if: ${{ github.event.workflow_run.conclusion == 'success' }}
     container:
       image: ${{ vars.CONTAINER_SOURCE }}/debian/gcc/release/abn:latest
     permissions:
       contents: write
     steps:
      - uses: actions/checkout@v4
      - name: Create build location
        run: |
            mkdir ${{ env.BUILD_LOC }}
        shell: bash
      - name: Disable renv
        run: |
            renv::deactivate()
        shell: Rscript {0}
      - name: Change permissions of configure
        run: |
            chmod +x configure
        shell: bash
      - name: Build the package
        run: |
            devtools::build(pkg = '.', path = '${{ env.BUILD_LOC }}/abn.tar.gz')
        shell: Rscript {0}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "${{ env.BUILD_LOC }}/abn.tar.gz"
