# Workflow to release a new version
# This action is adapted from https://github.com/t4d-gmbh/stubbed_versioning
name: Publish a version

on:
  pull_request:
    types:
      # TODO: we might also want to pusblish a version if the Pull request
      #       has conflicts, thus on 'closed' might be not enough
      - closed

jobs:
  release-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get the version to release
      id: release_version
      run: |
        echo "VERSION=$(echo ${{ github.head_ref }}|grep -Eo '[0-9]+.[0-9]+.[0-9]+')" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Creating the version tag
      run: |
        git config user.email "actions@github.com"
        git config user.name "github_actions"
        git tag -a ${{ steps.release_version.outputs.version }} -m 'Published Version'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        tags: true
    - uses: ncipollo/release-action@v1
      with:
        commit: ${{ github.head_ref }}  # NOTE: Asserts to not create release from main
        tag: ${{ steps.release_version.outputs.version }}
        # artifacts: "release.tar.gz,foo/*.txt"
        # bodyFile: "body.md"
        body: |
          Release of version ${{ steps.release_version.outputs.version }}
